// GENERATED by scripts/copy-vendor-css.js — do not edit by hand.
// Regenerated on every build; committed so `ng serve` works without a prebuild.

export const MATERIAL_CSS = '/assets/themes/material-70a77991.css';
export const PRISM_CSS = '/assets/themes/prism-be8e07d4.css';
